[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi-line-output = 3
line-length = 88

[tool.mypy]
python-version = "3.10"
warn-return-any = true
warn-unused-configs = true
disallow-untyped-defs = true
disallow-incomplete-defs = true

[tool.bandit]
exclude-dirs = ["tests"]
skips = ["B101"]

[tool.pytest.ini-options]
testpaths = ["tests"]
python-files = ["test_*.py"]
addopts = "-ra -q" 